language: node_js
node_js:
  - 'stable'

deploy_service_job: &DEPLOY_SERVICE_JOB
  cache:
    directories:
      - node_modules
      - ./aws-serverless/node_modules

install:
  - npm install -g serverless
  - travis_retry npm install
  - cd ./aws-serverless
  - travis_retry npm install
  - cd -

script:
  - cd ./aws-serverless
  - serverless deploy
